name: Import Combos CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


defaults:
  run:
    shell: bash


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: not-used
    steps:
      - id: semver
        name: Checkout ğŸ›ï¸
        uses: EasyDesk/action-semver-checkout@v1
      - name: Setup Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies ğŸ§¶
        run: pip install -r requirements.txt
        working-directory: backend
      - name: Run migrations ğŸš¢
        run: python manage.py migrate
        working-directory: backend
      - name: Import combos ğŸ§™
        run: python manage.py import_combos
        working-directory: backend
        continue-on-error: true
